name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  macos-test:
    name: Test on macOS
    runs-on: macOS-15
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app
    strategy:
      matrix:
        platform:
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 16"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=watchOS Simulator,name=Apple Watch Series 10 (42mm)"

    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests on ${{ matrix.platform }} for Swift package
        run: set -o pipefail && xcodebuild -scheme ReadingTime-Package -destination "${{ matrix.platform }}" test | xcbeautify

  linux-test:
    name: Test on Linux
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install the Swift toolchain
        uses: vapor/swiftly-action@v0.2.0
        with:
          toolchain: latest
      - name: Unit test on Linux
        run: swift test
