name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  macos-test:
    name: Test on macOS
    runs-on: macOS-15
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests for Swift package
        run: swift test
